/*modified by zhzhao<zhzhao@ingenic.cn>,20091103
 add function: support 24-bit bmp */



#include <stdio.h>
#include <stdlib.h>

#if defined(__linux__)
#include <stdint.h>
#else
#ifdef __CYGWIN__
#include "elf.h"
#else
#include <inttypes.h>
#endif
#endif

#include <config.h>


typedef struct bitmap_s {		/* bitmap description */
	uint16_t width;
	uint16_t height;
	uint8_t	palette[256*3];
	uint8_t	*data;
} bitmap_t;



#define DEFAULT_CMAP_SIZE	16	/* size of default color map	*/

/*
 * Neutralize little endians.
 */
uint16_t le_short(uint16_t x)
{
    uint16_t val;
    uint8_t *p = (uint8_t *)(&x);

    val =  (*p++ & 0xff) << 0;
    val |= (*p & 0xff) << 8;

    return val;
}

uint32_t le_int(uint32_t x)
{
    uint32_t val;
    uint8_t *p = (uint8_t *)(&x);

    val =  (*p++ & 0xff) << 0;
    val =  (*p++ & 0xff) << 8;
    val =  (*p++ & 0xff) << 16;
    val |= (*p & 0xff) << 24;

    return val;
}

void skip_bytes (FILE *fp, int n)
{
	while (n-- > 0)
		fgetc (fp);
}

int main (int argc, char *argv[])
{
	int	i, x;
	FILE	*fp;
	bitmap_t bmp;
	bitmap_t *b = &bmp;
	uint16_t data_offset, n_colors=0;

	int nbit;

#if defined(CONFIG_LCD)
#if LCD_BPP==4
	short val;
#elif LCD_BPP==5
	int val;
#endif
#endif

	if (argc < 2) {
		fprintf (stderr, "Usage: %s file\n", argv[0]);
		exit (EXIT_FAILURE);
	}

	if ((fp = fopen (argv[1], "rb")) == NULL) {
		perror (argv[1]);
		exit (EXIT_FAILURE);
	}

	if (fgetc (fp) != 'B' || fgetc (fp) != 'M') {
		fprintf (stderr, "%s is not a bitmap file.\n", argv[1]);
		exit (EXIT_FAILURE);
	}

	/*
	 * read width and height of the image, and the number of colors used;
	 * ignore the rest
	 */
	skip_bytes (fp, 8); //skip 8 byte
	fread (&data_offset, sizeof (uint16_t), 1, fp); //read size is 2
 	skip_bytes (fp, 6);
	fread (&b->width,   sizeof (uint16_t), 1, fp); //read size is 2
	skip_bytes (fp, 2);
	fread (&b->height,  sizeof (uint16_t), 1, fp);
	

	skip_bytes(fp,4);
	fread (&nbit,  sizeof (uint16_t), 1, fp);

	if(nbit == 24)
		skip_bytes (fp, 24);
	else{	
		skip_bytes (fp, 16);
		fread (&n_colors, sizeof (uint16_t), 1, fp);
		skip_bytes (fp, 6);
	}


	/*
	 * Repair endianess.
	 */
	data_offset = le_short(data_offset);
	b->width = le_short(b->width);
	b->height = le_short(b->height);
	n_colors = le_short(n_colors);


	/* whether file is 24bit or not */
	if(nbit == 24){
		
#if defined(CONFIG_LCD)
		if ( n_colors > 16777216 ) {
			n_colors = 16777216 ;
		}
		
#else
		if ((n_colors == 0) || (n_colors > 16777216 - DEFAULT_CMAP_SIZE)) {
		
			n_colors = 16777216 - DEFAULT_CMAP_SIZE;
		}
#endif
	}
	else { 
/* file is 8 bit*/
		
#if defined(CONFIG_LCD)
		if ( n_colors > 256 ) {
		n_colors = 256 ;
		}
		
#else
		if ((n_colors == 0) || (n_colors > 256 - DEFAULT_CMAP_SIZE)) {
			
			n_colors = 256 - DEFAULT_CMAP_SIZE;
		}
#endif
	}


	printf ("/*\n"
		" * Automatically generated by \"tools/bmp_logo\"\n"
		" *\n"
		" * DO NOT EDIT\n"
		" *\n"
		" */\n\n\n"
		"#ifndef __BMP_LOGO_H__\n"
		"#define __BMP_LOGO_H__\n\n"
		"#define BMP_LOGO_WIDTH\t\t%d\n"
		"#define BMP_LOGO_HEIGHT\t\t%d\n"
		"#define BMP_LOGO_COLORS\t\t%ld\n"
		"#define BMP_LOGO_OFFSET\t\t%d\n"
		"#define BMP_LOGO_BITS\t\t%ld\n"
		,
		b->width, b->height, n_colors,
		DEFAULT_CMAP_SIZE,nbit);
//		data_offset,nbit);

	/* allocate memory */
	if ((b->data = (uint8_t *)malloc(b->width * b->height * nbit/8)) == NULL) {

		fclose (fp);
		printf ("Error allocating memory for file %s.\n", argv[1]);
		exit (EXIT_FAILURE);
	}

//----------------------------read 8-bit bmp----------------------------------------------//
	if( nbit == 8){
		/* read and print the palette information */
		printf ("unsigned int bmp_logo_palette[] = {\n");
		
		for (i=0; i<n_colors; ++i) {
			b->palette[(int)(i*3+2)] = fgetc(fp);
			b->palette[(int)(i*3+1)] = fgetc(fp);
			b->palette[(int)(i*3+0)] = fgetc(fp);
			x=fgetc(fp);
			
#if defined(CONFIG_LCD)
			val = 0;
			
#if LCD_BPP==4 
		/* RGB565(16bits) */
			val = 	((b->palette[(int)(i*3+0)] >> 3) & 0x1F )<< 11 | \
				((b->palette[(int)(i*3+1)] >> 2) & 0x3F )<< 5  | \
				((b->palette[(int)(i*3+2)] >> 3) & 0x1F );
#elif LCD_BPP==5
		/* RGB666(18bits) */
			val = 	b->palette[(int)(i*3+0)] << 16 |	\
				b->palette[(int)(i*3+1)] << 8  |	\
				b->palette[(int)(i*3+2)] << 0 ;
#endif 
			printf ("%s0x%X,%s",
				((i%8) == 0) ? "\t" : "  ",
				val,
				((i%8) == 7) ? "\n" : ""
				);
		
#else
			printf ("%s0x0%X%X%X,%s",
				((i%8) == 0) ? "\t" : "  ",
				(b->palette[(int)(i*3+0)] >> 4) & 0x0F,
				(b->palette[(int)(i*3+1)] >> 4) & 0x0F,
				(b->palette[(int)(i*3+2)] >> 4) & 0x0F,
				((i%8) == 7) ? "\n" : ""
				);
#endif
		}
		
		
		
		/* seek to offset indicated by file header */
		fseek(fp, (long)data_offset, SEEK_SET);
	
		/* read the bitmap; leave room for default color map */
		
		printf ("\n");
		printf ("};\n");
		printf ("\n");
		printf ("unsigned char bmp_logo_bitmap[] = {\n");
		for (i=(b->height-1)*b->width; i>=0; i-=b->width) {
			for (x = 0; x < b->width; x++) {
#if defined(CONFIG_LCD)
				b->data[ i + x] = (uint8_t) fgetc (fp) ;
#else
				b->data[(uint16_t) i + x] = (uint8_t) fgetc (fp) \
					+ DEFAULT_CMAP_SIZE;
#endif
			}
	}
		fclose (fp);
		
		for (i=0; i<(b->height*b->width); ++i) {
			if ((i%8) == 0)
				putchar ('\t');
			printf ("0x%02X,%c",
				b->data[i],
				((i%8) == 7) ? '\n' : ' '
				);
	}
		printf ("\n"
			"};\n\n"
			"#endif /* __BMP_LOGO_H__ */\n"
			);

		
		
	} /* nbit == 8 end*/
//----------------------------read 24-bit bmp----------------------------------------------//
	else {
              /*get rgb of 24-bit file*/	

		uint8_t tmp1,tmp2,tmp3,tmp4;
		int value;
		int bitPerLine,i,j;
		int padding = 0;
		unsigned char data;

		bitPerLine  = ( (b->width*3)%4==0 ) ? b->width*3 : b->width*3 + (4- (b->width*3)%4) ;
		 /*padding width */
		padding = ( (b->width*3)%4==0 )? 0 : (4 - ((b->width * 3)) % 4); 

		printf(" // bitPerLine=%d \n",bitPerLine);

		printf ("unsigned int bmp_logo_palette[] = {\n");
		
		printf ("\n");
		printf ("};\n");


		printf ("\n");

		/* seek to offset indicated by file header */
		fseek(fp, (long)data_offset, SEEK_SET);
		printf ("unsigned int bmp_logo_bitmap[] = {\n");
		

		for (i=0; i < b->height; i++) { 
//		for (i=b->height; i>=1; i--) { // this is also ok.
			printf ("\n\n");	

			for (j=0; j< b->width; j++) {
	
				fread(&b->data,sizeof(uint8_t),1,fp);
				tmp1=b->data;
				fread(&b->data,sizeof(uint8_t),1,fp);	
				tmp2=b->data;
				fread(&b->data,sizeof(uint8_t),1,fp);	
				tmp3=b->data;
			
//you can use next three lines also.			
/* 
   tmp1=fgetc(fp);
   tmp2=fgetc(fp);
   tmp3=fgetc(fp);
*/			
		
				value=(tmp1 & 0xff) << 0 | (tmp2 & 0xff )<< 8 | ( tmp3 & 0xff )<< 16 ;

				printf (" 0x%06X, %s",
					value,
					((j%8) == 7) ? "\n" : ""
					);
				
			}
			
			if (padding) {
//				fprintf(stderr, "### Skip padding: 0x%x.\n", padding);

				fseek(fp, (long)padding, SEEK_CUR);
			}
		}
		
		fclose (fp);
		printf ("\n"
			"};\n\n"
			"#endif /* __BMP_LOGO_H__ */\n"
			);
		
	
	}
	


	return (0);
}
