#
# Makefile for jzchar
#
obj-$(CONFIG_JZCHAR)		+= jzchars.o

obj-$(CONFIG_JZ_SCC)		+= scc.o
obj-$(CONFIG_JZ_CIM)		+= cim.o
obj-$(CONFIG_JZ_TPANEL_ATA2508)	+= ata2508.o
obj-$(CONFIG_JZ_CAMERA_SENSOR)	+= sensor.o
obj-$(CONFIG_JZ_I2C_EEPROM)	+= eeprom.o
obj-$(CONFIG_JZ_EJTAG)		+= ejtag.o
obj-$(CONFIG_JZ_POWEROFF)	+= poweroff.o

obj-$(CONFIG_JZ_TPANEL)		+= jz_ts.o
obj-$(CONFIG_JZ_TPANEL_UCB1400)	+= ucb1400.o
obj-$(CONFIG_JZ_TPANEL_WM9712)	+= wm9712.o
obj-$(CONFIG_JZ_TPANEL_AK4182)	+= ak4182.o
obj-$(CONFIG_JZ_SADC)		+= sadc.o

obj-$(CONFIG_JZ_SMART_LCD)	+= slcd.o
obj-$(CONFIG_JZ_UDC_HOTPLUG)	+= udc_hotplug.o
obj-$(CONFIG_JZ_OW)	+= jz_ow.o
obj-$(CONFIG_JZ_TCSM)	+= tcsm.o
obj-$(CONFIG_JZ_TSSI)	+= jz_tssi.o
